Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> # This is a sample Python script.
... 
... # Press Shift+F10 to execute it or replace it with your code.
... # Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.
... 
... 
... def print_hi(name):
...     # Use a breakpoint in the code line below to debug your script.
...     print(f'Hi, {name}')  # Press Ctrl+F8 to toggle the breakpoint.
... 
... 
... # Press the green button in the gutter to run the script.
... if __name__ == '__main__':
...     print_hi('PyCharm')
... 
